package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/abigotado/confluence-cli/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const generatedNotice = "<!-- Code generated by tools/gencommands. DO NOT EDIT. -->"

type flagInfo struct {
	Name, Shorthand, Type, Default, Usage string
}

type commandInfo struct {
	Path, Short, Args string
	Flags             []flagInfo
}

type commandTree struct {
	Globals  []flagInfo
	Commands []commandInfo
}

func collect(root *cobra.Command) commandTree {
	var tree commandTree
	root.PersistentFlags().VisitAll(func(flag *pflag.Flag) {
		if !flag.Hidden {
			tree.Globals = append(tree.Globals, describeFlag(flag))
		}
	})
	var walk func(*cobra.Command)
	walk = func(command *cobra.Command) {
		for _, child := range command.Commands() {
			if child.Hidden || child.IsAdditionalHelpTopicCommand() || child.Name() == "help" || child.Name() == "completion" {
				continue
			}
			if child.HasSubCommands() {
				walk(child)
				continue
			}
			info := commandInfo{Path: child.CommandPath(), Short: child.Short}
			if _, args, found := strings.Cut(child.Use, " "); found {
				info.Args = args
			}
			inherited := child.InheritedFlags()
			child.LocalFlags().VisitAll(func(flag *pflag.Flag) {
				if !flag.Hidden && inherited.Lookup(flag.Name) == nil {
					info.Flags = append(info.Flags, describeFlag(flag))
				}
			})
			sort.Slice(info.Flags, func(i, j int) bool { return info.Flags[i].Name < info.Flags[j].Name })
			tree.Commands = append(tree.Commands, info)
		}
	}
	walk(root)
	sort.Slice(tree.Globals, func(i, j int) bool { return tree.Globals[i].Name < tree.Globals[j].Name })
	sort.Slice(tree.Commands, func(i, j int) bool { return tree.Commands[i].Path < tree.Commands[j].Path })
	return tree
}

func describeFlag(flag *pflag.Flag) flagInfo {
	defaultValue := flag.DefValue
	if defaultValue == "false" || defaultValue == "[]" {
		defaultValue = ""
	}
	return flagInfo{Name: flag.Name, Shorthand: flag.Shorthand, Type: flag.Value.Type(), Default: defaultValue, Usage: flag.Usage}
}

func renderMarkdown(tree commandTree) string {
	var builder strings.Builder
	builder.WriteString(generatedNotice + "\n\n# Command reference\n\n")
	builder.WriteString("JSON mode writes one stable envelope to stdout and is the default when stdout is not a TTY. Text, raw, and help output are explicitly selected exceptions. Network commands require an explicit `--profile`; there is no active or default profile. See `contract.md` for exit codes and envelopes.\n\n")
	builder.WriteString("## JSON response recovery\n\n")
	builder.WriteString("Apply this grammar in order:\n\n")
	builder.WriteString("1. A v1 envelope is exactly one complete top-level JSON object followed only by\n")
	builder.WriteString("   whitespace. It requires boolean `ok` and a JSON integer `v` whose value is\n")
	builder.WriteString("   exactly `1`. Decimal, exponent, string, null, boolean, and every other\n")
	builder.WriteString("   version representation is unsupported. If `ok` is `true`, `data` must be\n")
	builder.WriteString("   present and non-null; `error` and `hint` must be absent, and their presence\n")
	builder.WriteString("   is invalid even when `null`. If `ok` is `false`, `data` must be absent;\n")
	builder.WriteString("   `error` must be a present non-null object with string `code` and `message`,\n")
	builder.WriteString("   and `hint` must be a present string. Forbidden-key presence is invalid even\n")
	builder.WriteString("   when `null`. `meta` is optional; unknown additive fields are tolerated. They\n")
	builder.WriteString("   never repair an invalid known member. A valid v1 envelope is the primary\n")
	builder.WriteString("   result; never replace it with stderr. Any malformed or unsupported envelope\n")
	builder.WriteString("   makes stdout invalid.\n\n")
	builder.WriteString("   Valid v1 examples:\n\n")
	builder.WriteString("   `{" + `"ok":true,"v":1,"data":{},"meta":{"future":true},"future":true` + "}`\n\n")
	builder.WriteString("   `{" + `"ok":false,"v":1,"error":{"code":"PROFILE_REQUIRED","message":"profile is required","future":true},"hint":"pass --profile","future":true` + "}`\n\n")
	builder.WriteString("   Invalid examples:\n\n")
	builder.WriteString("   - `{" + `"ok":true,"v":2,"data":{}` + "}`\n")
	builder.WriteString("   - `{" + `"ok":true,"v":1.0,"data":{}` + "}`\n")
	builder.WriteString("   - `{" + `"ok":"true","v":1,"data":{}` + "}`\n")
	builder.WriteString("   - `{" + `"ok":true,"v":"1","data":{}` + "}`\n")
	builder.WriteString("   - `{" + `"ok":true,"v":1` + "}`\n")
	builder.WriteString("   - `{" + `"ok":true,"v":1,"data":null` + "}`\n")
	builder.WriteString("   - `{" + `"ok":true,"v":1,"data":{},"error":null` + "}`\n")
	builder.WriteString("   - `{" + `"ok":true,"v":1,"data":{},"hint":null` + "}`\n")
	builder.WriteString("   - `{" + `"ok":false,"v":1,"hint":"stop"` + "}`\n")
	builder.WriteString("   - `{" + `"ok":false,"v":1,"error":null,"hint":"stop"` + "}`\n")
	builder.WriteString("   - `{" + `"ok":false,"v":1,"error":{"code":1,"message":"failed"},"hint":"stop"` + "}`\n")
	builder.WriteString("   - `{" + `"ok":false,"v":1,"error":{"code":"FAILED","message":1},"hint":"stop"` + "}`\n")
	builder.WriteString("   - `{" + `"ok":false,"v":1,"error":{"code":"FAILED","message":"failed"},"hint":1` + "}`\n")
	builder.WriteString("   - `{" + `"ok":false,"v":1,"error":{"code":"FAILED","message":"failed"},"hint":"stop","data":null` + "}`\n\n")
	builder.WriteString("2. Only for a `confluence-cli pages create` or `confluence-cli pages update`\n")
	builder.WriteString("   invoked with both `--confirm-intent` and `--yes`, without `--dry-run`, whose\n")
	builder.WriteString("   stdout is empty, malformed, unsupported, or otherwise fails the complete v1\n")
	builder.WriteString("   grammar above, inspect at most the first 4096 bytes of stderr. Do not use\n")
	builder.WriteString("   stderr as a contract fallback in any other case.\n")
	builder.WriteString("3. In that bounded diagnostic, only one of these exact complete,\n")
	builder.WriteString("   newline-terminated lines counts\n")
	builder.WriteString("   as the known-applied marker:\n\n")
	builder.WriteString("   - `error: WRITE_APPLIED_LOCAL_FAILURE: pages.create applied, but local finalization failed`\n")
	builder.WriteString("   - `error: WRITE_APPLIED_LOCAL_FAILURE: pages.update applied, but local finalization failed`\n\n")
	builder.WriteString("   Match from the anchored `error: WRITE_APPLIED_LOCAL_FAILURE:` at line start\n")
	builder.WriteString("   through line end, never as a substring. This exact marker means known applied\n")
	builder.WriteString("   and no retry; the write must not be repeated.\n")
	builder.WriteString("4. Otherwise, do not retry and do not claim that the write applied. Use bounded\n")
	builder.WriteString("   Confluence reads to reconcile page ID, space, title, parent, version, and\n")
	builder.WriteString("   content before asking the operator about any further mutation.\n\n")
	builder.WriteString("## Global flags\n\n| Flag | Type | Description |\n| --- | --- | --- |\n")
	for _, flag := range tree.Globals {
		builder.WriteString(fmt.Sprintf("| %s | %s | %s |\n", flagLabel(flag), flag.Type, flag.Usage))
	}
	builder.WriteString("\n## Commands\n\n")
	for _, command := range tree.Commands {
		builder.WriteString("### `" + command.Path + "`\n\n")
		if command.Short != "" {
			builder.WriteString(command.Short + "\n\n")
		}
		if command.Args != "" {
			builder.WriteString("Usage: `" + command.Path + " " + command.Args + "`\n\n")
		}
		if len(command.Flags) == 0 {
			builder.WriteString("No flags of its own.\n\n")
			continue
		}
		builder.WriteString("| Flag | Type | Default | Description |\n| --- | --- | --- | --- |\n")
		for _, flag := range command.Flags {
			builder.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", flagLabel(flag), flag.Type, code(flag.Default), flag.Usage))
		}
		builder.WriteString("\n")
	}
	return strings.TrimRight(builder.String(), "\n") + "\n"
}

func flagLabel(flag flagInfo) string {
	if flag.Shorthand != "" {
		return fmt.Sprintf("`-%s, --%s`", flag.Shorthand, flag.Name)
	}
	return "`--" + flag.Name + "`"
}

func code(value string) string {
	if value == "" {
		return ""
	}
	return "`" + value + "`"
}

func rootCommand() *cobra.Command {
	return cli.NewApp().NewRootCommand()
}
