// Command gencontract renders the stable machine contract from internal/errx.
package main

import (
	"fmt"
	"strings"

	"github.com/abigotado/confluence-cli/internal/errx"
)

const generatedNotice = "<!-- Code generated by tools/gencontract. DO NOT EDIT. -->"

func renderMarkdown(contract errx.Contract) string {
	var output strings.Builder
	profileRequired := errx.ProfileRequired()
	output.WriteString(generatedNotice)
	output.WriteString("\n\n# Machine contract\n\n")
	output.WriteString("Regenerate with `go generate ./...`.\n\n")
	output.WriteString("## Envelope\n\n")
	_, _ = fmt.Fprintf(&output, "Current version: `%d`.\n\n", contract.EnvelopeVersion)
	output.WriteString("```json\n")
	_, _ = fmt.Fprintf(&output, `{"ok":true,"v":%d,"data":[{"id":"123","title":"Example"}],"meta":{"count":1,"truncated":true,"next_cursor":"opaque","profile":"work","site":"https://example.atlassian.net"}}`, contract.EnvelopeVersion)
	output.WriteByte('\n')
	_, _ = fmt.Fprintf(&output, `{"ok":false,"v":%d,"error":{"code":%q,"message":%q},"hint":%q}`, contract.EnvelopeVersion, profileRequired.Reason, profileRequired.Message, profileRequired.Hint)
	output.WriteString("\n```\n\n")
	output.WriteString("The top-level keys `ok`, `v`, `data`, `meta`, `error`, and `hint` are the\n")
	_, _ = fmt.Fprintf(&output, "v%d vocabulary. A field rename, removal, or type change requires an envelope\n", contract.EnvelopeVersion)
	output.WriteString("version bump. Optional `meta` fields are `count`, `truncated`, `next_cursor`,\n")
	output.WriteString("`profile`, and `site`; metadata never contains credentials.\n\n")
	output.WriteString("stdout receives exactly one compact JSON envelope in JSON mode. Diagnostics,\n")
	output.WriteString("prompts, warnings, and logs go to stderr. `error.code` is a stable\n")
	output.WriteString("`SCREAMING_SNAKE_CASE` value; add error detail there before considering a new\n")
	output.WriteString("process status.\n\n")
	output.WriteString("## JSON response recovery\n\n")
	output.WriteString("Apply this grammar in order:\n\n")
	output.WriteString("1. Parse stdout as exactly one JSON value. A single object with boolean `ok`\n")
	output.WriteString("   and integer `v` is the primary result; never replace it with stderr.\n")
	output.WriteString("2. Only for a `confluence-cli pages create` or `confluence-cli pages update`\n")
	output.WriteString("   invoked with both `--confirm-intent` and `--yes`, without `--dry-run`, whose\n")
	output.WriteString("   stdout is empty, fails JSON parsing\n")
	output.WriteString("   (including premature EOF), contains multiple JSON values, or lacks either\n")
	output.WriteString("   `ok` or `v`, inspect at most the first 4096 bytes of stderr. Do not use\n")
	output.WriteString("   stderr as a contract fallback in any other case.\n")
	output.WriteString("3. In that bounded diagnostic, only one of these exact complete,\n")
	output.WriteString("   newline-terminated lines counts\n")
	output.WriteString("   as the known-applied marker:\n\n")
	output.WriteString("   - `error: WRITE_APPLIED_LOCAL_FAILURE: pages.create applied, but local finalization failed`\n")
	output.WriteString("   - `error: WRITE_APPLIED_LOCAL_FAILURE: pages.update applied, but local finalization failed`\n\n")
	output.WriteString("   Match from the anchored `error: WRITE_APPLIED_LOCAL_FAILURE:` at line start\n")
	output.WriteString("   through line end, never as a substring. This exact marker means known applied\n")
	output.WriteString("   and no retry; the write must not be repeated.\n")
	output.WriteString("4. Otherwise, do not retry and do not claim that the write applied. Use bounded\n")
	output.WriteString("   Confluence reads to reconcile page ID, space, title, parent, version, and\n")
	output.WriteString("   content before asking the operator about any further mutation.\n\n")
	output.WriteString("## Exit codes\n\n")
	output.WriteString("Each status maps to a distinct caller recovery action.\n\n")
	output.WriteString("| Code | Name | Meaning | Caller's next move |\n")
	output.WriteString("| ---: | --- | --- | --- |\n")
	for _, info := range contract.Codes {
		_, _ = fmt.Fprintf(&output, "| %d | `%s` | %s | %s |\n", info.Code, info.Name, info.Meaning, info.NextMove)
	}
	output.WriteString("\n## Recovery rules\n\n")
	output.WriteString("- Treat `403` as permission/scope denial (exit 8), not authentication.\n")
	output.WriteString("- Treat `409` as stale state/conflict (exit 9); re-read before another write.\n")
	output.WriteString("- Follow `next_cursor`; a full page does not prove the result is complete.\n")
	output.WriteString("- A compiled Go runtime can exit 2 after an unrecovered panic. The process entry\n")
	output.WriteString("  must recover ordinary panics and report exit 1 so they are not mistaken for\n")
	output.WriteString("  correct usage failures.\n")
	output.WriteString("- `confluence-cli contract` exposes the same table as JSON at runtime.\n")
	return output.String()
}
